### ISSUE TITLE
process-compose gets stuck on quit if clickhouse init db fails

### ISSUE THREAD

**Issue by conscious-puppet** [juspay/services-flake#361]
process-compose gets stuck on quit if the the clickhouse init db service fails. we need to manually kill the clickhouse process.

the issue can be reproduced by using a malformed initial db dump with the clickhouse service.

[![asciicast](https://asciinema.org/a/dEXn6hpILm7NFaL5kalVn6yRi.svg)](https://asciinema.org/a/dEXn6hpILm7NFaL5kalVn6yRi)

**Comment by shivaraj-bh** [comment]
Here’s the culprit:
https://github.com/juspay/services-flake/blob/deaa2b81d07d2e7ec2ee74e91e17020d31bf3cb7/nix/services/clickhouse/default.nix#L120-L125

During `init` the server starts and because the schema files have errors, and exits with non-zero exit-code, the script stops before killing the server.

**Comment by shivaraj-bh** [comment]
The easiest fix is to run the shell script without breaking on errors in any intermediate command. 

But, I would like to see if we can just avoid starting the `clickhouse-server` in the init script, by just waiting for the server process to start and init the schemas. 

pinging @roman-bodavskiy to see if you have any opinion on this as you worked on this in https://github.com/juspay/services-flake/pull/91
