### ISSUE TITLE
Kafka & zookeeper

### ISSUE THREAD

**Issue by srid** [juspay/services-flake#41]
We need this for https://github.com/nammayatri/location-tracking-service/issues/34

**Comment by shivaraj-bh** [comment]
kafka can be based on: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/apache-kafka.nix
and zookeeper on: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/zookeeper.nix

Since kafka depends on zookeeper the process should never start when used standalone
